export const REQUEST_SENT = 'LOGIN_SUBMITED';
export const REQUEST_ERROR = 'REQUEST_ERROR';
export const LOGIN_REQUEST_COMPLETE = 'LOGIN_REQUEST_COMPLETE';
export const REGISTER_REQUEST_COMPLETE = 'REGISTER_REQUEST_COMPLETE';
